#mysql ˝æ›ø‚µÿ÷∑
spring:
    datasource:
        username: root
        password: Lenin1918
        url: jdbc:mysql://47.106.239.211:3306/cdi_bigdata_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
        driverClassName: com.mysql.cj.jdbc.Driver

# mybatis≈‰÷√
mybatis:
    mapper-locations: /mapper/*Mapper.xml
    #type-aliases-package: com.cdibd.elasticsearch